export { AcademicStats } from './AcademicStats'
export { AcademicFilterBar } from './AcademicFilterBar'
export { NoteCard } from './NoteCard'
export { NoteModal } from './NoteModal'
export { SubjectManagerModal } from './SubjectManagerModal'
export { AcademicView } from './AcademicView'
export type { AcademicViewHandle, AcademicViewProps } from './AcademicView'
export { SUBJECT_COLORS, getSubjectColor } from './academicColors'
